version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - echo "Listing contents of the current directory:"
      - ls -la
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; else echo "requirements.txt not found"; fi
  pre_build:
    commands:
      - echo "Pre-build phase started"
  build:
    commands:
      - echo "Build phase started"
      - zip -r lambda_function.zip .
  post_build:
    commands:
      - echo "Build phase completed"
      - ls -la  # List directory contents after build
artifacts:
  files:
    - lambda_function.zip
